# =============================================================================
# HMM (Hidden Markov Model) CONFIGURATION
# =============================================================================

# -----------------------------------------------------------------------------
# 1. PATHS
# -----------------------------------------------------------------------------
paths:
  raw_data_dir: "data/03_processed/keypoints/training"
  model_dir: "data/04_models/HMM"
  report_dir: "data/05_results/hmm"

# -----------------------------------------------------------------------------
# 2. MODEL PARAMETERS
# -----------------------------------------------------------------------------
n_states: 8
n_iter: 500
random_state: 83376
grasp_state: 7

# -----------------------------------------------------------------------------
# 3. REGIONS OF INTEREST (ROI) DEFINITION
# -----------------------------------------------------------------------------
roi_centers:
  - [0.3109, 0.7780]
  - [0.4356, 0.7904]
  - [0.5578, 0.7835]
  - [0.7116, 0.6859]

# -----------------------------------------------------------------------------
# 4. THRESHOLDS & BOUNDARIES
# -----------------------------------------------------------------------------
roi_threshold: 0.06
roi_rad_x: 0.06
roi_rad_y: 0.15
min_y_for_grasp: 0.55
